### ISSUE TITLE
Cpu miner bug - testnet ALFA 

### ISSUE THREAD

**Issue by dimdumon** [kaspanet/kaspad#1461]
After running cpu miner for couple of hours I got this:
```
2021-01-27 20:48:23.304 [INF] KSMN: Current hash rate is 401.52 Khash/s
2021-01-27 20:48:33.305 [INF] KSMN: Current hash rate is 382.46 Khash/s
2021-01-27 20:48:34.665 [INF] KSMN: Got timeout while requesting block template from localhost:16210
2021-01-27 20:48:34.665 [INF] KSMN: Found block 16693189990fd9c8a673864b803420efc5405eb0af0e83634aefac13e8ee0f82 with parents [1be4d4262e43588cacb40aae20ca745cf6e586431de890ebd0b72d8e5f4b3e7e 5bc598cef70e189fbc88fe769717ef1155d5c5a97a710ae556e922c1886d592a]. Submitting to localhost:16210
2021-01-27 20:48:43.304 [INF] KSMN: Current hash rate is 0.00 Khash/s
2021-01-27 20:48:44.665 [CRT] KSMN: Exiting: Fatal error in goroutine `mineLoop 3`: Error submitting block 16693189990fd9c8a673864b803420efc5405eb0af0e83634aefac13e8ee0f82 to localhost:16210: got timeout after 10s: timeout expired
main.handleFoundBlock
        C:/dev/kaspad/cmd/kaspaminer/mineloop.go:124
main.mineLoop.func1
        C:/dev/kaspad/cmd/kaspaminer/mineloop.go:53
github.com/kaspanet/kaspad/util/panics.handleSpawnedFunction
        C:/dev/kaspad/util/panics/panics.go:84
github.com/kaspanet/kaspad/util/panics.GoroutineWrapperFunc.func1.1
        C:/dev/kaspad/util/panics/panics.go:32
runtime.goexit
        c:/go/src/runtime/asm_amd64.s:1374
error in mine loop
main.main.func1
        C:/dev/kaspad/cmd/kaspaminer/main.go:53
github.com/kaspanet/kaspad/util/panics.handleSpawnedFunction
        C:/dev/kaspad/util/panics/panics.go:84
github.com/kaspanet/kaspad/util/panics.GoroutineWrapperFunc.func1.1
        C:/dev/kaspad/util/panics/panics.go:32
runtime.goexit
        c:/go/src/runtime/asm_amd64.s:1374
2021-01-27 20:48:44.666 [CRT] KSMN: Goroutine stack trace: goroutine 1 [running]:
runtime/debug.Stack(0x1f, 0xc000227e08, 0x135a65)
        c:/go/src/runtime/debug/stack.go:24 +0xa5
github.com/kaspanet/kaspad/util/panics.GoroutineWrapperFunc.func1(0x7e06fc, 0x8, 0xc00030a540)
        C:/dev/kaspad/util/panics/panics.go:30 +0x36
main.main()
        C:/dev/kaspad/cmd/kaspaminer/main.go:50 +0x41a

2021-01-27 20:48:44.667 [CRT] KSMN: Stack trace: goroutine 13 [running]:
runtime/debug.Stack(0x7f1ac2, 0x22, 0xc00060fbd0)
        c:/go/src/runtime/debug/stack.go:24 +0xa5
github.com/kaspanet/kaspad/util/panics.HandlePanic(0xc0003080a0, 0xc000314920, 0xa, 0xc0003b0c00, 0x13d, 0x400)
        C:/dev/kaspad/util/panics/panics.go:22 +0x10a
panic(0x75d360, 0xc0010ad720)
        c:/go/src/runtime/panic.go:969 +0x1c7
main.main.func1()
        C:/dev/kaspad/cmd/kaspaminer/main.go:53 +0x10e
github.com/kaspanet/kaspad/util/panics.handleSpawnedFunction(0xc0003080a0, 0xc0003b0c00, 0x13d, 0x400, 0x7e06fc, 0x8, 0xc00030a540)
        C:/dev/kaspad/util/panics/panics.go:84 +0x2ce
github.com/kaspanet/kaspad/util/panics.GoroutineWrapperFunc.func1.1(0xc0003080a0, 0xc0003b0c00, 0x13d, 0x400, 0x7e06fc, 0x8, 0xc00030a540)
        C:/dev/kaspad/util/panics/panics.go:32 +0x6e
created by github.com/kaspanet/kaspad/util/panics.GoroutineWrapperFunc.func1
        C:/dev/kaspad/util/panics/panics.go:31 +0x93

Exiting...
```

**Comment by someone235** [comment]
Some rare blocks (e.g. the one that moves the pruning point) takes more than 10 seconds to validate, so instead of crashing the miner should only log timeout errors

**Comment by stasatdaglabs** [comment]
Should be fixed by: https://github.com/kaspanet/kaspad/pull/1462
