### ISSUE TITLE
Crash during tx submission

### ISSUE THREAD

**Issue by aspect** [kaspanet/kaspad#1601]
Platform: OS X
A crash occurred during a large tx submission (large = tx with a lot of UTXOs):

```
2021-03-11 05:30:13.494 [INF] BDAG: Processed 12 blocks and 0 headers in the last 10.43s (63 transactions, 2021-03-11 05:30:12.308 +0530 IST)
2021-03-11 05:30:13.494 [INF] PROT: Accepted block 3dbc704359038107a0a0591f104f9314776ed7737fbfeac8895b57acebcdbb93 via relay
2021-03-11 05:30:13.532 [INF] PROT: Accepted block 0e5f1e6620f1c9c805da39204d24f9d09c5a683dec2c6c14ffbb59167bbdd4ee via relay
2021-03-11 05:30:15.806 [INF] PROT: Accepted block e80f8c58c0ceffaad9df23e8b69b73ab93054dc89379a888ef1070316c52915d via relay
2021-03-11 05:30:16.213 [INF] PROT: Accepted block 3011428bfd07d5dfe2b45ff584aba2a68d6920d5e1f751094372690caf01c256 via relay
2021-03-11 05:30:17.805 [INF] PROT: Accepted block 91fb488dc9f9ad420849275f65ac3baee4cc1028528ad0d77098b9f304d7ed86 via relay
fatal error: concurrent map read and map write

goroutine 303 [running]:
runtime.throw(0x4910cb2, 0x21)
  /usr/local/go/src/runtime/panic.go:1116 +0x72 fp=0xc02498b648 sp=0xc02498b618 pc=0x403a172
runtime.mapaccess2_faststr(0x47f1900, 0xc00bbd5920, 0xc031426e80, 0x1b, 0x1, 0x1)
  /usr/local/go/src/runtime/map_faststr.go:116 +0x4a5 fp=0xc02498b6b8 sp=0xc02498b648 pc=0x4017a05
github.com/kaspanet/kaspad/app/rpc/rpccontext.(*NotificationListener).convertUTXOChangesToUTXOsChangedNotification(0xc01837e270, 0xc01822f180, 0xc057495540)
  /emanator/go/src/github.com/kaspanet/kaspad/app/rpc/rpccontext/notificationmanager.go:277 +0x16e fp=0xc02498b8d8 sp=0xc02498b6b8 pc=0x46dccce
github.com/kaspanet/kaspad/app/rpc/rpccontext.(*NotificationManager).NotifyUTXOsChanged(0xc00ab7ea80, 0xc01822f180, 0x0, 0x0)
  /emanator/go/src/github.com/kaspanet/kaspad/app/rpc/rpccontext/notificationmanager.go:148 +0x11f fp=0xc02498b990 sp=0xc02498b8d8 pc=0x46dc3bf
github.com/kaspanet/kaspad/app/rpc.(*Manager).notifyUTXOsChanged(0xc00ab65070, 0xc0436e4300, 0x0, 0x0)
  /emanator/go/src/github.com/kaspanet/kaspad/app/rpc/manager.go:123 +0xe5 fp=0xc02498b9d8 sp=0xc02498b990 pc=0x46e7365
github.com/kaspanet/kaspad/app/rpc.(*Manager).NotifyBlockAddedToDAG(0xc00ab65070, 0xc035bd24e0, 0xc0436e4300, 0x0, 0x0)
  /emanator/go/src/github.com/kaspanet/kaspad/app/rpc/manager.go:56 +0x270 fp=0xc02498ba48 sp=0xc02498b9d8 pc=0x46e6ed0
github.com/kaspanet/kaspad/app/rpc.(*Manager).NotifyBlockAddedToDAG-fm(0xc035bd24e0, 0xc0436e4300, 0x49233c5, 0x3b)
  /emanator/go/src/github.com/kaspanet/kaspad/app/rpc/manager.go:51 +0x3e fp=0xc02498ba80 sp=0xc02498ba48 pc=0x46ed09e
github.com/kaspanet/kaspad/app/protocol/flowcontext.(*FlowContext).OnNewBlock(0xc00ab8fa40, 0xc035bd24e0, 0xc0436e4300, 0x0, 0x0)
  /emanator/go/src/github.com/kaspanet/kaspad/app/protocol/flowcontext/blocks.go:50 +0x6e6 fp=0xc02498bc18 sp=0xc02498ba80 pc=0x46cebe6
github.com/kaspanet/kaspad/app/protocol/flowcontext.(*FlowContext).AddBlock(0xc00ab8fa40, 0xc035bd24e0, 0xc029a00b00, 0xc03b34fd00)
  /emanator/go/src/github.com/kaspanet/kaspad/app/protocol/flowcontext/blocks.go:122 +0x225 fp=0xc02498bcb8 sp=0xc02498bc18 pc=0x46cf0e5
github.com/kaspanet/kaspad/app/protocol.(*Manager).AddBlock(...)
  /emanator/go/src/github.com/kaspanet/kaspad/app/protocol/manager.go:53
github.com/kaspanet/kaspad/app/rpc/rpchandlers.HandleSubmitBlock(0xc00ab712c0, 0xc044e9bda0, 0x49f2ae0, 0xc035bd24b0, 0x1, 0xc029a00b00, 0x0, 0x0)
  /emanator/go/src/github.com/kaspanet/kaspad/app/rpc/rpchandlers/submit_block.go:27 +0x19f fp=0xc02498bd60 sp=0xc02498bcb8 pc=0x46e5c5f
github.com/kaspanet/kaspad/app/rpc.(*Manager).handleIncomingMessages(0xc00ab65070, 0xc044e9bda0, 0xc031b28c80, 0xc02a494600, 0x2c)
  /emanator/go/src/github.com/kaspanet/kaspad/app/rpc/rpc.go:79 +0xf0 fp=0xc02498bdd8 sp=0xc02498bd60 pc=0x46e7bb0
github.com/kaspanet/kaspad/app/rpc.(*Manager).routerInitializer.func1()
  /emanator/go/src/github.com/kaspanet/kaspad/app/rpc/rpc.go:63 +0x85 fp=0xc02498be40 sp=0xc02498bdd8 pc=0x46e7e85
github.com/kaspanet/kaspad/util/panics.handleSpawnedFunction(0xc0002fc4b0, 0xc00b86f000, 0xb0a, 0x1000, 0x4917aad, 0x28, 0xc044e9be60)
  /emanator/go/src/github.com/kaspanet/kaspad/util/panics/panics.go:83 +0x2c7 fp=0xc02498bf60 sp=0xc02498be40 pc=0x4451607
github.com/kaspanet/kaspad/util/panics.GoroutineWrapperFunc.func1.1(0xc0002fc4b0, 0xc00b86f000, 0xb0a, 0x1000, 0x4917aad, 0x28, 0xc044e9be60)
  /emanator/go/src/github.com/kaspanet/kaspad/util/panics/panics.go:32 +0x67 fp=0xc02498bfa8 sp=0xc02498bf60 pc=0x4451767
runtime.goexit()
  /usr/local/go/src/runtime/asm_amd64.s:1374 +0x1 fp=0xc02498bfb0 sp=0xc02498bfa8 pc=0x4072701
created by github.com/kaspanet/kaspad/util/panics.GoroutineWrapperFunc.func1
  /emanator/go/src/github.com/kaspanet/kaspad/util/panics/panics.go:31 +0x8c

```

**Comment by aspect** [comment]
Another crash (seems also map related):

```
goroutine 303 [running]:
runtime.throw(0x4910cb2, 0x21)
	/usr/local/go/src/runtime/panic.go:1116 +0x72 fp=0xc02498b648 sp=0xc02498b618 pc=0x403a172
runtime.mapaccess2_faststr(0x47f1900, 0xc00bbd5920, 0xc031426e80, 0x1b, 0x1, 0x1)
	/usr/local/go/src/runtime/map_faststr.go:116 +0x4a5 fp=0xc02498b6b8 sp=0xc02498b648 pc=0x4017a05
github.com/kaspanet/kaspad/app/rpc/rpccontext.(*NotificationListener).convertUTXOChangesToUTXOsChangedNotification(0xc01837e270, 0xc01822f180, 0xc057495540)
	/emanator/go/src/github.com/kaspanet/kaspad/app/rpc/rpccontext/notificationmanager.go:277 +0x16e fp=0xc02498b8d8 sp=0xc02498b6b8 pc=0x46dccce
github.com/kaspanet/kaspad/app/rpc/rpccontext.(*NotificationManager).NotifyUTXOsChanged(0xc00ab7ea80, 0xc01822f180, 0x0, 0x0)
	/emanator/go/src/github.com/kaspanet/kaspad/app/rpc/rpccontext/notificationmanager.go:148 +0x11f fp=0xc02498b990 sp=0xc02498b8d8 pc=0x46dc3bf
github.com/kaspanet/kaspad/app/rpc.(*Manager).notifyUTXOsChanged(0xc00ab65070, 0xc0436e4300, 0x0, 0x0)
	/emanator/go/src/github.com/kaspanet/kaspad/app/rpc/manager.go:123 +0xe5 fp=0xc02498b9d8 sp=0xc02498b990 pc=0x46e7365
github.com/kaspanet/kaspad/app/rpc.(*Manager).NotifyBlockAddedToDAG(0xc00ab65070, 0xc035bd24e0, 0xc0436e4300, 0x0, 0x0)
	/emanator/go/src/github.com/kaspanet/kaspad/app/rpc/manager.go:56 +0x270 fp=0xc02498ba48 sp=0xc02498b9d8 pc=0x46e6ed0
github.com/kaspanet/kaspad/app/rpc.(*Manager).NotifyBlockAddedToDAG-fm(0xc035bd24e0, 0xc0436e4300, 0x49233c5, 0x3b)
	/emanator/go/src/github.com/kaspanet/kaspad/app/rpc/manager.go:51 +0x3e fp=0xc02498ba80 sp=0xc02498ba48 pc=0x46ed09e
github.com/kaspanet/kaspad/app/protocol/flowcontext.(*FlowContext).OnNewBlock(0xc00ab8fa40, 0xc035bd24e0, 0xc0436e4300, 0x0, 0x0)
	/emanator/go/src/github.com/kaspanet/kaspad/app/protocol/flowcontext/blocks.go:50 +0x6e6 fp=0xc02498bc18 sp=0xc02498ba80 pc=0x46cebe6
github.com/kaspanet/kaspad/app/protocol/flowcontext.(*FlowContext).AddBlock(0xc00ab8fa40, 0xc035bd24e0, 0xc029a00b00, 0xc03b34fd00)
	/emanator/go/src/github.com/kaspanet/kaspad/app/protocol/flowcontext/blocks.go:122 +0x225 fp=0xc02498bcb8 sp=0xc02498bc18 pc=0x46cf0e5
github.com/kaspanet/kaspad/app/protocol.(*Manager).AddBlock(...)
	/emanator/go/src/github.com/kaspanet/kaspad/app/protocol/manager.go:53
github.com/kaspanet/kaspad/app/rpc/rpchandlers.HandleSubmitBlock(0xc00ab712c0, 0xc044e9bda0, 0x49f2ae0, 0xc035bd24b0, 0x1, 0xc029a00b00, 0x0, 0x0)
	/emanator/go/src/github.com/kaspanet/kaspad/app/rpc/rpchandlers/submit_block.go:27 +0x19f fp=0xc02498bd60 sp=0xc02498bcb8 pc=0x46e5c5f
github.com/kaspanet/kaspad/app/rpc.(*Manager).handleIncomingMessages(0xc00ab65070, 0xc044e9bda0, 0xc031b28c80, 0xc02a494600, 0x2c)
	/emanator/go/src/github.com/kaspanet/kaspad/app/rpc/rpc.go:79 +0xf0 fp=0xc02498bdd8 sp=0xc02498bd60 pc=0x46e7bb0
github.com/kaspanet/kaspad/app/rpc.(*Manager).routerInitializer.func1()
	/emanator/go/src/github.com/kaspanet/kaspad/app/rpc/rpc.go:63 +0x85 fp=0xc02498be40 sp=0xc02498bdd8 pc=0x46e7e85
github.com/kaspanet/kaspad/util/panics.handleSpawnedFunction(0xc0002fc4b0, 0xc00b86f000, 0xb0a, 0x1000, 0x4917aad, 0x28, 0xc044e9be60)
	/emanator/go/src/github.com/kaspanet/kaspad/util/panics/panics.go:83 +0x2c7 fp=0xc02498bf60 sp=0xc02498be40 pc=0x4451607
github.com/kaspanet/kaspad/util/panics.GoroutineWrapperFunc.func1.1(0xc0002fc4b0, 0xc00b86f000, 0xb0a, 0x1000, 0x4917aad, 0x28, 0xc044e9be60)
	/emanator/go/src/github.com/kaspanet/kaspad/util/panics/panics.go:32 +0x67 fp=0xc02498bfa8 sp=0xc02498bf60 pc=0x4451767
runtime.goexit()
	/usr/local/go/src/runtime/asm_amd64.s:1374 +0x1 fp=0xc02498bfb0 sp=0xc02498bfa8 pc=0x4072701
created by github.com/kaspanet/kaspad/util/panics.GoroutineWrapperFunc.func1
	/emanator/go/src/github.com/kaspanet/kaspad/util/panics/panics.go:31 +0x8c

```
