### ISSUE TITLE
kapsawallet on windows panic on keys.getPassword

### ISSUE THREAD

**Issue by demisrael** [kaspanet/kaspad#1707]
```
[dima.dima-PC] ➤ ./kaspawallet.exe send --testnet --rpcserver=10.0.0.26:16210 --to-address=kaspatest:blabla --send-amount=100
panic: The handle is invalid.

goroutine 1 [running]:
github.com/kaspanet/kaspad/cmd/kaspawallet/keys.getPassword(0xebdf95, 0x9, 0xc0036fdda0, 0xb4350e, 0xc00368b3c0)
        C:/Users/aspect/emanator/go/src/github.com/kaspanet/kaspad/cmd/kaspawallet/keys/get_password.go:16 +0x2b9
github.com/kaspanet/kaspad/cmd/kaspawallet/keys.(*Data).DecryptPrivateKeys(0xc000067000, 0x1, 0x1, 0x1, 0xc0002cfeb8, 0x2)
        C:/Users/aspect/emanator/go/src/github.com/kaspanet/kaspad/cmd/kaspawallet/keys/keys.go:113 +0x4f
main.send(0xc0000689c0, 0x4, 0xe242e0)
        C:/Users/aspect/emanator/go/src/github.com/kaspanet/kaspad/cmd/kaspawallet/send.go:68 +0x427
main.main()
        C:/Users/aspect/emanator/go/src/github.com/kaspanet/kaspad/cmd/kaspawallet/main.go:15 +0x9b
```

**Comment by someone235** [comment]
Couldn't reproduce on a Windows machine. Can you give more details to reproduce?

**Comment by demisrael** [comment]
missing dependency. I'm not sure which package is missing, compiled on same machine.

**Comment by demisrael** [comment]
 18/05/2021   18:18.03   /home/mobaxterm  go list ...
archive/tar
archive/zip
bufio
bytes
compress/bzip2
compress/flate
compress/gzip
compress/lzw
compress/zlib
container/heap
container/list
container/ring
context
crypto
crypto/aes
crypto/cipher
crypto/des
crypto/dsa
crypto/ecdsa
crypto/ed25519
crypto/ed25519/internal/edwards25519
crypto/elliptic
crypto/hmac
crypto/internal/randutil
crypto/internal/subtle
crypto/md5
crypto/rand
crypto/rc4
crypto/rsa
crypto/sha1
crypto/sha256
crypto/sha512
crypto/subtle
crypto/tls
crypto/x509
crypto/x509/pkix
database/sql
database/sql/driver
debug/dwarf
debug/elf
debug/gosym
debug/macho
debug/pe
debug/plan9obj
embed
embed/internal/embedtest
encoding
encoding/ascii85
encoding/asn1
encoding/base32
encoding/base64
encoding/binary
encoding/csv
encoding/gob
encoding/hex
encoding/json
encoding/pem
encoding/xml
errors
expvar
flag
fmt
go/ast
go/build
go/build/constraint
go/constant
go/doc
go/format
go/importer
go/internal/gccgoimporter
go/internal/gcimporter
go/internal/srcimporter
go/parser
go/printer
go/scanner
go/token
go/types
hash
hash/adler32
hash/crc32
hash/crc64
hash/fnv
hash/maphash
html
html/template
image
image/color
image/color/palette
image/draw
image/gif
image/internal/imageutil
image/jpeg
image/png
index/suffixarray
internal/bytealg
internal/cfg
internal/cpu
internal/execabs
internal/fmtsort
internal/goroot
internal/goversion
internal/lazyregexp
internal/lazytemplate
internal/nettrace
internal/obscuretestdata
internal/oserror
internal/poll
internal/profile
internal/race
internal/reflectlite
internal/singleflight
internal/syscall/execenv
internal/syscall/windows
internal/syscall/windows/registry
internal/syscall/windows/sysdll
internal/sysinfo
internal/testenv
internal/testlog
internal/trace
internal/unsafeheader
internal/xcoff
io
io/fs
io/ioutil
log
log/syslog
math
math/big
math/bits
math/cmplx
math/rand
mime
mime/multipart
mime/quotedprintable
net
net/http
net/http/cgi
net/http/cookiejar
net/http/fcgi
net/http/httptest
net/http/httptrace
net/http/httputil
net/http/internal
net/http/pprof
net/internal/socktest
net/mail
net/rpc
net/rpc/jsonrpc
net/smtp
net/textproto
net/url
os
os/exec
os/signal
os/user
path
path/filepath
plugin
reflect
regexp
regexp/syntax
runtime
runtime/cgo
runtime/debug
runtime/internal/atomic
runtime/internal/math
runtime/internal/sys
runtime/metrics
runtime/pprof
runtime/race
runtime/trace
sort
strconv
strings
sync
sync/atomic
syscall
testing
testing/fstest
testing/internal/testdeps
testing/iotest
testing/quick
text/scanner
text/tabwriter
text/template
text/template/parse
time
time/tzdata
unicode
unicode/utf16
unicode/utf8
unsafe
cmd/addr2line
cmd/api
cmd/asm
cmd/asm/internal/arch
cmd/asm/internal/asm
cmd/asm/internal/flags
cmd/asm/internal/lex
cmd/buildid
cmd/cgo
cmd/compile
cmd/compile/internal/amd64
cmd/compile/internal/arm
cmd/compile/internal/arm64
cmd/compile/internal/gc
cmd/compile/internal/logopt
cmd/compile/internal/mips
cmd/compile/internal/mips64
cmd/compile/internal/ppc64
cmd/compile/internal/riscv64
cmd/compile/internal/s390x
cmd/compile/internal/ssa
cmd/compile/internal/syntax
cmd/compile/internal/test
cmd/compile/internal/types
cmd/compile/internal/wasm
cmd/compile/internal/x86
cmd/cover
cmd/dist
cmd/doc
cmd/fix
cmd/go
cmd/go/internal/auth
cmd/go/internal/base
cmd/go/internal/bug
cmd/go/internal/cache
cmd/go/internal/cfg
cmd/go/internal/clean
cmd/go/internal/cmdflag
cmd/go/internal/doc
cmd/go/internal/envcmd
cmd/go/internal/fix
cmd/go/internal/fmtcmd
cmd/go/internal/fsys
cmd/go/internal/generate
cmd/go/internal/get
cmd/go/internal/help
cmd/go/internal/imports
cmd/go/internal/list
cmd/go/internal/load
cmd/go/internal/lockedfile
cmd/go/internal/lockedfile/internal/filelock
cmd/go/internal/modcmd
cmd/go/internal/modconv
cmd/go/internal/modfetch
cmd/go/internal/modfetch/codehost
cmd/go/internal/modfetch/zip_sum_test
cmd/go/internal/modget
cmd/go/internal/modinfo
cmd/go/internal/modload
cmd/go/internal/mvs
cmd/go/internal/par
cmd/go/internal/renameio
cmd/go/internal/robustio
cmd/go/internal/run
cmd/go/internal/search
cmd/go/internal/str
cmd/go/internal/test
cmd/go/internal/tool
cmd/go/internal/trace
cmd/go/internal/txtar
cmd/go/internal/vcs
cmd/go/internal/version
cmd/go/internal/vet
cmd/go/internal/web
cmd/go/internal/work
cmd/gofmt
cmd/internal/archive
cmd/internal/bio
cmd/internal/browser
cmd/internal/buildid
cmd/internal/codesign
cmd/internal/diff
cmd/internal/dwarf
cmd/internal/edit
cmd/internal/gcprog
cmd/internal/goobj
cmd/internal/moddeps
cmd/internal/obj
cmd/internal/obj/arm
cmd/internal/obj/arm64
cmd/internal/obj/mips
cmd/internal/obj/ppc64
cmd/internal/obj/riscv
cmd/internal/obj/s390x
cmd/internal/obj/wasm
cmd/internal/obj/x86
cmd/internal/objabi
cmd/internal/objfile
cmd/internal/pkgpath
cmd/internal/src
cmd/internal/sys
cmd/internal/test2json
cmd/internal/traceviewer
cmd/link
cmd/link/internal/amd64
cmd/link/internal/arm
cmd/link/internal/arm64
cmd/link/internal/benchmark
cmd/link/internal/ld
cmd/link/internal/loadelf
cmd/link/internal/loader
cmd/link/internal/loadmacho
cmd/link/internal/loadpe
cmd/link/internal/loadxcoff
cmd/link/internal/mips
cmd/link/internal/mips64
cmd/link/internal/ppc64
cmd/link/internal/riscv64
cmd/link/internal/s390x
cmd/link/internal/sym
cmd/link/internal/wasm
cmd/link/internal/x86
cmd/nm
cmd/objdump
cmd/pack
cmd/pprof
cmd/test2json
cmd/trace
cmd/vet
