### ISSUE TITLE
Kaspad - v0.12.13 - Fatal error in goroutine `flow-HandleIBD 18`: failed to clear imported pruning point data leveldb/table: corruption`

### ISSUE THREAD

**Issue by blackmennewstyle** [kaspanet/kaspad#2219]
I'm trying to run `kaspad` on `testnet` but the node always crashes at the same point:
```
2023-09-02 02:38:18.018 [CRT] PROT: Exiting: Fatal error in goroutine `flow-HandleIBD 18`: failed to clear imported pruning point data: leveldb/table: corruption on data-block (pos=1196025): checksum mismatch, want=0xc06276d2 got=0x9c0ffdcb [file=005404.ldb]
```
`kaspad.conf`:
```
[Application Options]
testnet=1
uacomment=kaspa-testnet.cedric-crispin.com
utxoindex=1
maxinpeers=25
outpeers=4
enablebanning=1
listen=:16211
rpclisten=:16210
rpcmaxclients=5
rpcmaxwebsockets=5
rpcmaxconcurrentreqs=5
; Debug logging level.
; Valid levels are {trace, debug, info, warn, error, critical}
; You may also specify <subsystem>=<level>,<subsystem2>=<level>,... to set
; log level for individual subsystems. Use kaspad --loglevel=show to list
; available subsystems.
loglevel=debug
```
`kaspad_err.log`
```
2023-09-02 02:38:18.018 [CRT] PROT: Exiting: Fatal error in goroutine `flow-HandleIBD 18`: failed to clear imported pruning point data: leveldb/table: corruption on data-block (pos=1196025): checksum mismatch, want=0xc06276d2 got=0x9c0ffdcb [file=005404.ldb]
2023-09-02 02:38:18.018 [CRT] PROT: Goroutine stack trace: goroutine 63 [running]:
runtime/debug.Stack()
	/usr/local/go/src/runtime/debug/stack.go:24 +0x65
github.com/kaspanet/kaspad/util/panics.GoroutineWrapperFunc.func1({0xc0002bbcc0, 0xe}, 0xc0001668e0)
	/home/ceedii/kaspad-0.12.13/util/panics/panics.go:30 +0x35
github.com/kaspanet/kaspad/app/protocol.(*Manager).runFlows(0xd5ee80?, {0xc016928600, 0x14, 0xc00032be58?}, 0xc0168ca140, 0xc01687fad0?, 0xc0002bbcb0)
	/home/ceedii/kaspad-0.12.13/app/protocol/manager.go:85 +0x65
github.com/kaspanet/kaspad/app/protocol.(*Manager).routerInitializer.func1()
	/home/ceedii/kaspad-0.12.13/app/protocol/protocol.go:94 +0x6e5
github.com/kaspanet/kaspad/util/panics.handleSpawnedFunction(0xc00020f3b0, {0xc0169fd000, 0x97a, 0x1000}, {0xc62e09?, 0xc0167c9780?}, 0xc00017c410)
	/home/ceedii/kaspad-0.12.13/util/panics/panics.go:83 +0x250
github.com/kaspanet/kaspad/util/panics.GoroutineWrapperFunc.func1.1()
	/home/ceedii/kaspad-0.12.13/util/panics/panics.go:32 +0x35
created by github.com/kaspanet/kaspad/util/panics.GoroutineWrapperFunc.func1
	/home/ceedii/kaspad-0.12.13/util/panics/panics.go:31 +0xf8

2023-09-02 02:38:18.018 [CRT] PROT: Stack trace: goroutine 81 [running]:
runtime/debug.Stack()
	/usr/local/go/src/runtime/debug/stack.go:24 +0x65
github.com/kaspanet/kaspad/util/panics.HandlePanic(0xc000185998?, {0xc016a3c000, 0x11}, {0xc016eb8000, 0x440, 0x800})
	/home/ceedii/kaspad-0.12.13/util/panics/panics.go:22 +0xf4
panic({0xb1b9e0, 0xc061b7d9b0})
	/usr/local/go/src/runtime/panic.go:884 +0x213
github.com/kaspanet/kaspad/app/protocol/flows/v5/blockrelay.(*handleIBDFlow).fetchMissingUTXOSet.func1()
	/home/ceedii/kaspad-0.12.13/app/protocol/flows/v5/blockrelay/ibd_with_headers_proof.go:417 +0x99
github.com/kaspanet/kaspad/app/protocol/flows/v5/blockrelay.(*handleIBDFlow).fetchMissingUTXOSet(0xc016a3e000, {0xd6afd8, 0xc000038500}, 0xc030fadda0)
	/home/ceedii/kaspad-0.12.13/app/protocol/flows/v5/blockrelay/ibd_with_headers_proof.go:428 +0x2b1
github.com/kaspanet/kaspad/app/protocol/flows/v5/blockrelay.(*handleIBDFlow).syncPruningPointUTXOSet(0xc016a3e000, {0xd6afd8, 0xc000038500}, 0xc030fadda0)
	/home/ceedii/kaspad-0.12.13/app/protocol/flows/v5/blockrelay/ibd_with_headers_proof.go:398 +0x117
github.com/kaspanet/kaspad/app/protocol/flows/v5/blockrelay.(*handleIBDFlow).downloadHeadersAndPruningUTXOSet(0xc016a3e000, 0x200?, 0xc0170eae00?, 0x44?)
	/home/ceedii/kaspad-0.12.13/app/protocol/flows/v5/blockrelay/ibd_with_headers_proof.go:192 +0x212
github.com/kaspanet/kaspad/app/protocol/flows/v5/blockrelay.(*handleIBDFlow).ibdWithHeadersProof(0xc016a3e000, 0xc674d2?, 0x0?, 0x0?)
	/home/ceedii/kaspad-0.12.13/app/protocol/flows/v5/blockrelay/ibd_with_headers_proof.go:22 +0x7b
github.com/kaspanet/kaspad/app/protocol/flows/v5/blockrelay.(*handleIBDFlow).runIBDIfNotRunning(0xc016a3e000, 0xc00037b560)
	/home/ceedii/kaspad-0.12.13/app/protocol/flows/v5/blockrelay/ibd.go:103 +0x307
github.com/kaspanet/kaspad/app/protocol/flows/v5/blockrelay.(*handleIBDFlow).start(0xc016a3e000)
	/home/ceedii/kaspad-0.12.13/app/protocol/flows/v5/blockrelay/ibd.go:59 +0x58
github.com/kaspanet/kaspad/app/protocol/flows/v5/blockrelay.HandleIBD(...)
	/home/ceedii/kaspad-0.12.13/app/protocol/flows/v5/blockrelay/ibd.go:49
github.com/kaspanet/kaspad/app/protocol/flows/v5.registerBlockRelayFlows.func3(0xc016d728d0, 0xc0168ca140)
	/home/ceedii/kaspad-0.12.13/app/protocol/flows/v5/register.go:84 +0xca
github.com/kaspanet/kaspad/app/protocol.(*Manager).registerFlowForRoute.func1(0x10?)
	/home/ceedii/kaspad-0.12.13/app/protocol/protocol.go:168 +0x59
github.com/kaspanet/kaspad/app/protocol.(*Manager).runFlows.func1()
	/home/ceedii/kaspad-0.12.13/app/protocol/manager.go:86 +0x2a
github.com/kaspanet/kaspad/util/panics.handleSpawnedFunction(0xc00020f3b0, {0xc016eb8000, 0x440, 0x800}, {0xc0002bbcc0?, 0x0?}, 0xc0001668e0)
	/home/ceedii/kaspad-0.12.13/util/panics/panics.go:83 +0x250
github.com/kaspanet/kaspad/util/panics.GoroutineWrapperFunc.func1.1()
	/home/ceedii/kaspad-0.12.13/util/panics/panics.go:32 +0x35
created by github.com/kaspanet/kaspad/util/panics.GoroutineWrapperFunc.func1
	/home/ceedii/kaspad-0.12.13/util/panics/panics.go:31 +0xf8


```

**Comment by someone235** [comment]
The go implementation is deprecated: Any pull requests or issues that will be opened in this repository will be closed without treatment, except for issues or pull requests related to the kaspawallet, which remains maintained. In any other case, please use the [Rust implementation](https://github.com/kaspanet/rusty-kaspa) instead.
