### ISSUE TITLE
kaspad cannot start

### ISSUE THREAD

**Issue by HofiOne** [kaspanet/kaspad#2238]
tried multiple versions, the latest release from here, an older version embedded in kdx, same result

deleting the database, solves only the issue

```
2023-11-30 09:15:45.707 [CRT] PROT: Exiting: Fatal error in goroutine `flow-HandleRelayInvs 21`: not found
key 012f72656163686162696c6974792d646174612f6749d93e6b648729548946a35ac07151213026ec35ab2060d00053a16d4949c2 not found
github.com/kaspanet/kaspad/infrastructure/db/database/ldb.(*LevelDB).Get
	/Users/surindersingh/emanator/go/src/github.com/kaspanet/kaspad/infrastructure/db/database/ldb/leveldb.go:76
github.com/kaspanet/kaspad/domain/consensus/database.(*dbManager).Get
	/Users/surindersingh/emanator/go/src/github.com/kaspanet/kaspad/domain/consensus/database/dbmanager.go:13
github.com/kaspanet/kaspad/domain/consensus/datastructures/reachabilitydatastore.(*reachabilityDataStore).ReachabilityData
	/Users/surindersingh/emanator/go/src/github.com/kaspanet/kaspad/domain/consensus/datastructures/reachabilitydatastore/reachability_data_store.go:93
github.com/kaspanet/kaspad/domain/consensus/processes/reachabilitymanager.(*reachabilityManager).interval
	/Users/surindersingh/emanator/go/src/github.com/kaspanet/kaspad/domain/consensus/processes/reachabilitymanager/fetch.go:34
github.com/kaspanet/kaspad/domain/consensus/processes/reachabilitymanager.(*reachabilityManager).IsReachabilityTreeAncestorOf
	/Users/surindersingh/emanator/go/src/github.com/kaspanet/kaspad/domain/consensus/processes/reachabilitymanager/tree.go:137
github.com/kaspanet/kaspad/domain/consensus/processes/dagtopologymanager.(*dagTopologyManager).IsInSelectedParentChainOf
	/Users/surindersingh/emanator/go/src/github.com/kaspanet/kaspad/domain/consensus/processes/dagtopologymanager/dagtopologymanager.go:119
github.com/kaspanet/kaspad/domain/consensus/processes/dagtopologymanager.(*dagTopologyManager).ChildInSelectedParentChainOf
	/Users/surindersingh/emanator/go/src/github.com/kaspanet/kaspad/domain/consensus/processes/dagtopologymanager/dagtopologymanager.go:210
github.com/kaspanet/kaspad/domain/consensus/processes/mergedepthmanager.(*mergeDepthManager).calculateMergeDepthRoot
	/Users/surindersingh/emanator/go/src/github.com/kaspanet/kaspad/domain/consensus/processes/mergedepthmanager/merge_depth_manager.go:247
github.com/kaspanet/kaspad/domain/consensus/processes/mergedepthmanager.(*mergeDepthManager).VirtualMergeDepthRoot
	/Users/surindersingh/emanator/go/src/github.com/kaspanet/kaspad/domain/consensus/processes/mergedepthmanager/merge_depth_manager.go:142
github.com/kaspanet/kaspad/domain/consensus.(*consensus).VirtualMergeDepthRoot
	/Users/surindersingh/emanator/go/src/github.com/kaspanet/kaspad/domain/consensus/consensus.go:1108
github.com/kaspanet/kaspad/app/protocol/flows/v5/blockrelay.(*handleRelayInvsFlow).start
	/Users/surindersingh/emanator/go/src/github.com/kaspanet/kaspad/app/protocol/flows/v5/blockrelay/handle_relay_invs.go:151
github.com/kaspanet/kaspad/app/protocol/flows/v5/blockrelay.HandleRelayInvs
	/Users/surindersingh/emanator/go/src/github.com/kaspanet/kaspad/app/protocol/flows/v5/blockrelay/handle_relay_invs.go:66
github.com/kaspanet/kaspad/app/protocol/flows/v5.registerBlockRelayFlows.func2
	/Users/surindersingh/emanator/go/src/github.com/kaspanet/kaspad/app/protocol/flows/v5/register.go:69
github.com/kaspanet/kaspad/app/protocol.(*Manager).RegisterFlow.(*Manager).registerFlowForRoute.func1
	/Users/surindersingh/emanator/go/src/github.com/kaspanet/kaspad/app/protocol/protocol.go:168
github.com/kaspanet/kaspad/app/protocol.(*Manager).runFlows.func1
	/Users/surindersingh/emanator/go/src/github.com/kaspanet/kaspad/app/protocol/manager.go:86
github.com/kaspanet/kaspad/util/panics.handleSpawnedFunction
	/Users/surindersingh/emanator/go/src/github.com/kaspanet/kaspad/util/panics/panics.go:83
github.com/kaspanet/kaspad/app/protocol.init.GoroutineWrapperFunc.func1.1
	/Users/surindersingh/emanator/go/src/github.com/kaspanet/kaspad/util/panics/panics.go:32
runtime.goexit
	/usr/local/go/src/runtime/asm_amd64.s:1650
2023-11-30 09:15:45.707 [CRT] PROT: Goroutine stack trace: goroutine 83 [running]:
runtime/debug.Stack()
	/usr/local/go/src/runtime/debug/stack.go:24 +0x5e
github.com/kaspanet/kaspad/app/protocol.init.GoroutineWrapperFunc.func1({0xc007f9a078, 0x14}, 0xc007f8e280)
	/Users/surindersingh/emanator/go/src/github.com/kaspanet/kaspad/util/panics/panics.go:30 +0x2f
github.com/kaspanet/kaspad/app/protocol.(*Manager).runFlows(0x10095a660?, {0xc0000a2700, 0x14, 0xc007fb5e58?}, 0xc008036280, 0xc018d8a270?, 0xc007f9c0a0)
	/Users/surindersingh/emanator/go/src/github.com/kaspanet/kaspad/app/protocol/manager.go:85 +0x6e
github.com/kaspanet/kaspad/app/protocol.(*Manager).routerInitializer.func1()
	/Users/surindersingh/emanator/go/src/github.com/kaspanet/kaspad/app/protocol/protocol.go:94 +0x6af
github.com/kaspanet/kaspad/util/panics.handleSpawnedFunction(0xc0001fd350, {0xc018da4000, 0xb85, 0x1000}, {0x10085873e?, 0x0?}, 0xc018d801e0)
	/Users/surindersingh/emanator/go/src/github.com/kaspanet/kaspad/util/panics/panics.go:83 +0x244
github.com/kaspanet/kaspad/app/protocol.init.GoroutineWrapperFunc.func1.1()
	/Users/surindersingh/emanator/go/src/github.com/kaspanet/kaspad/util/panics/panics.go:32 +0x2f
created by github.com/kaspanet/kaspad/app/protocol.init.GoroutineWrapperFunc.func1 in goroutine 38
	/Users/surindersingh/emanator/go/src/github.com/kaspanet/kaspad/util/panics/panics.go:31 +0xe9

2023-11-30 09:15:45.707 [CRT] PROT: Stack trace: goroutine 16 [running]:
runtime/debug.Stack()
	/usr/local/go/src/runtime/debug/stack.go:24 +0x5e
github.com/kaspanet/kaspad/util/panics.HandlePanic(0x100736a98?, {0xc01904c018, 0x17}, {0xc007fc2800, 0x538, 0x800})
	/Users/surindersingh/emanator/go/src/github.com/kaspanet/kaspad/util/panics/panics.go:22 +0xf4
panic({0x10079b620?, 0xc01900e2d0?})
	/usr/local/go/src/runtime/panic.go:914 +0x21f
github.com/kaspanet/kaspad/app/protocol/flowcontext.(*FlowContext).HandleError(0x1000125a5, {0x1009524a0, 0xc01900e2d0}, {0x10084f250, 0xf}, 0xc018d86040, 0x148d478f8?)
	/Users/surindersingh/emanator/go/src/github.com/kaspanet/kaspad/app/protocol/flowcontext/errors.go:28 +0x2a5
github.com/kaspanet/kaspad/app/protocol.(*Manager).RegisterFlow.(*Manager).registerFlowForRoute.func1(0x10?)
	/Users/surindersingh/emanator/go/src/github.com/kaspanet/kaspad/app/protocol/protocol.go:170 +0x85
github.com/kaspanet/kaspad/app/protocol.(*Manager).runFlows.func1()
	/Users/surindersingh/emanator/go/src/github.com/kaspanet/kaspad/app/protocol/manager.go:86 +0x27
github.com/kaspanet/kaspad/util/panics.handleSpawnedFunction(0xc0001fd350, {0xc007fc2800, 0x538, 0x800}, {0xc007f9a078?, 0x0?}, 0xc007f8e280)
	/Users/surindersingh/emanator/go/src/github.com/kaspanet/kaspad/util/panics/panics.go:83 +0x244
github.com/kaspanet/kaspad/app/protocol.init.GoroutineWrapperFunc.func1.1()
	/Users/surindersingh/emanator/go/src/github.com/kaspanet/kaspad/util/panics/panics.go:32 +0x2f
created by github.com/kaspanet/kaspad/app/protocol.init.GoroutineWrapperFunc.func1 in goroutine 83
	/Users/surindersingh/emanator/go/src/github.com/kaspanet/kaspad/util/panics/panics.go:31 +0xe9

2023-11-30 09:15:45.728 [CRT] PROT: Exiting: Fatal error in goroutine `flow-HandleRelayInvs 41`: not found
reachability data not found
github.com/kaspanet/kaspad/domain/consensus/datastructures/reachabilitydatastore.init
	/Users/surindersingh/emanator/go/src/github.com/kaspanet/kaspad/domain/consensus/datastructures/reachabilitydatastore/reachability_data_store.go:76
runtime.doInit1
	/usr/local/go/src/runtime/proc.go:6740
runtime.doInit
	/usr/local/go/src/runtime/proc.go:6707
runtime.main
	/usr/local/go/src/runtime/proc.go:249
runtime.goexit
	/usr/local/go/src/runtime/asm_amd64.s:1650
panic: Writing to the logger when it's not running

goroutine 144 [running]:
github.com/kaspanet/kaspad/infrastructure/logger.(*Logger).printf(0xc0001fd350, 0x5, {0x100845f8b, 0x4}, {0x10084c009, 0xb}, {0xc007fb1fc0, 0x1, 0x1})
	/Users/surindersingh/emanator/go/src/github.com/kaspanet/kaspad/infrastructure/logger/logs.go:184 +0x365
github.com/kaspanet/kaspad/infrastructure/logger.(*Logger).Writef(...)
	/Users/surindersingh/emanator/go/src/github.com/kaspanet/kaspad/infrastructure/logger/logs.go:143
github.com/kaspanet/kaspad/infrastructure/logger.(*Logger).Criticalf(0xc00807c480?, {0x10084c009?, 0x10006aeb9?}, {0xc007fb1fc0?, 0xc000478f00?, 0xc0080018f0?})
	/Users/surindersingh/emanator/go/src/github.com/kaspanet/kaspad/infrastructure/logger/logs.go:126 +0x4c
github.com/kaspanet/kaspad/util/panics.exit.func1()
	/Users/surindersingh/emanator/go/src/github.com/kaspanet/kaspad/util/panics/panics.go:57 +0xa6
created by github.com/kaspanet/kaspad/util/panics.exit in goroutine 79
	/Users/surindersingh/emanator/go/src/github.com/kaspanet/kaspad/util/panics/panics.go:56 +0x17c
```

**Comment by someone235** [comment]
The go implementation is deprecated: Any pull requests or issues that will be opened in this repository will be closed without treatment, except for issues or pull requests related to the kaspawallet, which remains maintained. In any other case, please use the [Rust implementation](https://github.com/kaspanet/rusty-kaspa) instead.
