### ISSUE TITLE
Exiting: Fatal error in goroutine `flow-HandleRelayInvs 1296`: not found key 

### ISSUE THREAD

**Issue by N0TScrooge** [kaspanet/kaspad#2289]
Full node
The node was turned off for some time (it so happened), turned it on, synchronized, worked a little and...

```
2024-08-14 17:25:54.337 [INF] NTAR: Disconnected from <263d05538f97a08ec09c7179f7b4bc07: 207.127.90.53:48920>
2024-08-14 17:50:15.402 [INF] TXMP: P2P Incoming connection from 156.67.63.17:33322 #7
2024-08-14 17:50:15.754 [INF] PROT: Registering p2p flows for peer <b8ec08d71a80f6255d519e4ad150760d: 156.67.63.17:33322> for protocol version 5
2024-08-14 17:52:15.932 [INF] NTAR: Disconnected from <b8ec08d71a80f6255d519e4ad150760d: 156.67.63.17:33322>
2024-08-14 18:11:44.558 [INF] TXMP: P2P Incoming connection from 159.196.185.9:60474 #7
2024-08-14 18:11:44.727 [INF] PROT: Registering p2p flows for peer <e825cc6758c84997b904d06ef85c824e: 159.196.185.9:60474> for protocol version 5
2024-08-14 18:11:44.901 [CRT] PROT: Exiting: Fatal error in goroutine `flow-HandleRelayInvs 1296`: not found
key 012f002f626c6f636b2d67686f73746461672d646174612f76f18d70f9210e066fcc5ef4cdf4a2e2a04fd37325e081884805a244c22715bf not found
github.com/kaspanet/kaspad/infrastructure/db/database/ldb.(*LevelDB).Get
        /home/kaspa/kaspad/infrastructure/db/database/ldb/leveldb.go:76
github.com/kaspanet/kaspad/domain/consensus/database.(*dbManager).Get
        /home/kaspa/kaspad/domain/consensus/database/dbmanager.go:13
github.com/kaspanet/kaspad/domain/consensus/datastructures/ghostdagdatastore.(*ghostdagDataStore).Get
        /home/kaspa/kaspad/domain/consensus/datastructures/ghostdagdatastore/ghostdag_data_store.go:59
github.com/kaspanet/kaspad/domain/consensus.(*consensus).GetBlockInfo
        /home/kaspa/kaspad/domain/consensus/consensus.go:444
github.com/kaspanet/kaspad/app/protocol/flows/v5/blockrelay.(*handleRelayInvsFlow).start
        /home/kaspa/kaspad/app/protocol/flows/v5/blockrelay/handle_relay_invs.go:82
github.com/kaspanet/kaspad/app/protocol/flows/v5/blockrelay.HandleRelayInvs
        /home/kaspa/kaspad/app/protocol/flows/v5/blockrelay/handle_relay_invs.go:66
github.com/kaspanet/kaspad/app/protocol/flows/v5.registerBlockRelayFlows.func2
        /home/kaspa/kaspad/app/protocol/flows/v5/register.go:69
github.com/kaspanet/kaspad/app/protocol.(*Manager).RegisterFlow.(*Manager).registerFlowForRoute.func1
        /home/kaspa/kaspad/app/protocol/protocol.go:168
github.com/kaspanet/kaspad/app/protocol.(*Manager).runFlows.func1
        /home/kaspa/kaspad/app/protocol/manager.go:86
github.com/kaspanet/kaspad/util/panics.handleSpawnedFunction
        /home/kaspa/kaspad/util/panics/panics.go:83
github.com/kaspanet/kaspad/app/protocol.init.GoroutineWrapperFunc.func1.1
        /home/kaspa/kaspad/util/panics/panics.go:32
runtime.goexit
        /home/kaspa/go1.22.4/go/src/runtime/asm_amd64.s:1695
2024-08-14 18:11:44.901 [CRT] PROT: Goroutine stack trace: goroutine 1746 [running]:
runtime/debug.Stack()
        /home/kaspa/go1.22.4/go/src/runtime/debug/stack.go:24 +0x5e
github.com/kaspanet/kaspad/app/protocol.init.GoroutineWrapperFunc.func1({0xc074fa00d8, 0x14}, 0xc02439a080)
        /home/kaspa/kaspad/util/panics/panics.go:30 +0x2f
github.com/kaspanet/kaspad/app/protocol.(*Manager).runFlows(0xc06b1afb60?, {0xc04ce34000, 0x14, 0xc0738cb920?}, 0xc0000cdd60, 0xc0738cb920, 0xc02558a010)
        /home/kaspa/kaspad/app/protocol/manager.go:85 +0x6e
github.com/kaspanet/kaspad/app/protocol.(*Manager).routerInitializer.func1()
        /home/kaspa/kaspad/app/protocol/protocol.go:94 +0x68f
github.com/kaspanet/kaspad/util/panics.handleSpawnedFunction(0xc0002908a0, {0xc01fec9000, 0x93e, 0x1000}, {0xc5ca12?, 0x95cee5?}, 0xc08155dc70)
        /home/kaspa/kaspad/util/panics/panics.go:83 +0x247
github.com/kaspanet/kaspad/app/protocol.init.GoroutineWrapperFunc.func1.1()
        /home/kaspa/kaspad/util/panics/panics.go:32 +0x2f
created by github.com/kaspanet/kaspad/app/protocol.init.GoroutineWrapperFunc.func1 in goroutine 1553
        /home/kaspa/kaspad/util/panics/panics.go:31 +0xcb

2024-08-14 18:11:44.902 [CRT] PROT: Stack trace: goroutine 1751 [running]:
runtime/debug.Stack()
        /home/kaspa/go1.22.4/go/src/runtime/debug/stack.go:24 +0x5e
github.com/kaspanet/kaspad/util/panics.HandlePanic(0xc0002908a0, {0xc085cd0000, 0x19}, {0xc024390800, 0x43a, 0x800})
        /home/kaspa/kaspad/util/panics/panics.go:22 +0xe9
panic({0xb9dce0?, 0xc076ef4078?})
        /home/kaspa/go1.22.4/go/src/runtime/panic.go:770 +0x132
github.com/kaspanet/kaspad/app/protocol/flowcontext.(*FlowContext).HandleError(0xc07eabedb0?, {0xd5d360, 0xc076ef4078}, {0xc531df, 0xf}, 0xc04b0a72a0, 0xc0738cb920)
        /home/kaspa/kaspad/app/protocol/flowcontext/errors.go:28 +0x2af
github.com/kaspanet/kaspad/app/protocol.(*Manager).RegisterFlow.(*Manager).registerFlowForRoute.func1(0x10?)
        /home/kaspa/kaspad/app/protocol/protocol.go:170 +0x85
github.com/kaspanet/kaspad/app/protocol.(*Manager).runFlows.func1()
        /home/kaspa/kaspad/app/protocol/manager.go:86 +0x24
github.com/kaspanet/kaspad/util/panics.handleSpawnedFunction(0xc0002908a0, {0xc024390800, 0x43a, 0x800}, {0xc074fa00d8?, 0x95cee5?}, 0xc02439a080)
        /home/kaspa/kaspad/util/panics/panics.go:83 +0x247
github.com/kaspanet/kaspad/app/protocol.init.GoroutineWrapperFunc.func1.1()
        /home/kaspa/kaspad/util/panics/panics.go:32 +0x2f
created by github.com/kaspanet/kaspad/app/protocol.init.GoroutineWrapperFunc.func1 in goroutine 1746
        /home/kaspa/kaspad/util/panics/panics.go:31 +0xcb

2024-08-14 18:11:48.358 [INF] KASD: Version 0.12.17
2024-08-14 18:11:48.359 [INF] KASD: Loading database from '/home/kaspauser/.kaspad/kaspa-mainnet/datadir2'
2024-08-14 18:11:56.139 [INF] PRFX: Deleting database prefix &{1}

```

**Comment by someone235** [comment]
The go implementation is deprecated: Any pull requests or issues that will be opened in this repository will be closed without treatment, except for issues or pull requests related to the kaspawallet, which remains maintained. In any other case, please use the [Rust implementation](https://github.com/kaspanet/rusty-kaspa) instead.
